[package]
name = "snip_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "snip_rust"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.100"
env_logger = "0.11.8"
image = "0.25.8"
screenshots = "0.8.10"
winit = "0.30.12"

[[example]]
name = "capture_demo"
path = "examples/capture_demo.rs"
