[package]
name = "snip-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.10", features = ["image", "advanced"] }
tray-item = "0.8"
snip-core = { path = "../snip-core" }
tokio = { version = "1.0", features = ["full"] }
log = "0.4"
anyhow = "1.0"
