[package]
name = "snip-core"
version = "0.1.0"
edition = "2021"

[dependencies]
screenshots = "0.8"
image = "0.24"
global-hotkey = "0.5"
tokio = { version = "1.0", features = ["full"] }
log = "0.4"
anyhow = "1.0"
thiserror = "1.0"
